spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: false

logging:
  level:
    com.attendance.saas: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    enabled: true
