spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
  flyway:
    clean-disabled: true

server:
  forward-headers-strategy: framework

logging:
  level:
    root: WARN
    com.attendance.saas: INFO

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
