package com.attendance.saas.exception;

import org.springframework.http.HttpStatus;

/**
 * Stable, machine-readable error codes returned to API clients.
 */
public enum ErrorCode {

    // generic
    VALIDATION_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),
    BAD_REQUEST(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    CONFLICT(HttpStatus.CONFLICT),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    // authentication
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    USER_INACTIVE(HttpStatus.FORBIDDEN),
    COMPANY_INACTIVE(HttpStatus.FORBIDDEN),
    WEAK_PASSWORD(HttpStatus.UNPROCESSABLE_ENTITY),

    // tenant / resources
    COMPANY_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMPANY_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    COMPANY_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    TENANT_NOT_RESOLVED(HttpStatus.FORBIDDEN),
    CROSS_TENANT_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    INVALID_TIMEZONE(HttpStatus.UNPROCESSABLE_ENTITY),

    // organisation structure
    DEPARTMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    DEPARTMENT_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT),
    DEPARTMENT_IN_USE(HttpStatus.CONFLICT),
    POSITION_NOT_FOUND(HttpStatus.NOT_FOUND),
    POSITION_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT),
    POSITION_IN_USE(HttpStatus.CONFLICT),

    // employees
    EMPLOYEE_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMPLOYEE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    EMPLOYEE_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    EMPLOYEE_ALREADY_HAS_ACCOUNT(HttpStatus.CONFLICT),
    ROLE_NOT_GRANTABLE(HttpStatus.FORBIDDEN),
    EMPLOYEE_INACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_EMPLOYEE_PROFILE(HttpStatus.NOT_FOUND),

    // shifts
    SHIFT_NOT_FOUND(HttpStatus.NOT_FOUND),
    SHIFT_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT),
    SHIFT_IN_USE(HttpStatus.CONFLICT),
    INVALID_SHIFT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_SHIFT_ASSIGNED(HttpStatus.UNPROCESSABLE_ENTITY),
    SHIFT_ASSIGNMENT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_DATE_RANGE(HttpStatus.UNPROCESSABLE_ENTITY),

    // attendance
    ATTENDANCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    ALREADY_CHECKED_IN(HttpStatus.CONFLICT),
    ALREADY_CHECKED_OUT(HttpStatus.CONFLICT),
    NOT_CHECKED_IN(HttpStatus.UNPROCESSABLE_ENTITY),
    CHECK_OUT_BEFORE_CHECK_IN(HttpStatus.UNPROCESSABLE_ENTITY),

    // geofencing
    LOCATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    LOCATION_NAME_ALREADY_EXISTS(HttpStatus.CONFLICT),
    NO_ACTIVE_LOCATION(HttpStatus.UNPROCESSABLE_ENTITY),
    LOCATION_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    OUTSIDE_GEOFENCE(HttpStatus.UNPROCESSABLE_ENTITY),

    // leave
    LEAVE_NOT_FOUND(HttpStatus.NOT_FOUND),
    LEAVE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    LEAVE_NOT_PENDING(HttpStatus.CONFLICT),
    CANNOT_REVIEW_OWN_REQUEST(HttpStatus.FORBIDDEN),
    NOT_REQUEST_OWNER(HttpStatus.FORBIDDEN),

    // attendance correction
    CORRECTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    CORRECTION_ALREADY_EXISTS(HttpStatus.CONFLICT),
    CORRECTION_NOT_PENDING(HttpStatus.CONFLICT),
    INVALID_CORRECTION(HttpStatus.UNPROCESSABLE_ENTITY),

    // plans and subscriptions
    PLAN_NOT_FOUND(HttpStatus.NOT_FOUND),
    PLAN_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    PLAN_IN_USE(HttpStatus.CONFLICT),
    PLAN_INACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBSCRIPTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    SUBSCRIPTION_NOT_ACTIVE(HttpStatus.PAYMENT_REQUIRED),
    EMPLOYEE_LIMIT_REACHED(HttpStatus.PAYMENT_REQUIRED),
    LOCATION_LIMIT_REACHED(HttpStatus.PAYMENT_REQUIRED),
    USER_LIMIT_REACHED(HttpStatus.PAYMENT_REQUIRED),
    FEATURE_NOT_IN_PLAN(HttpStatus.PAYMENT_REQUIRED),

    // invoicing
    INVOICE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVOICE_ALREADY_SETTLED(HttpStatus.CONFLICT);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus getStatus() {
        return status;
    }
}
